### PR TITLE
Update Python and Django versions in test

### PR DESCRIPTION
**Pull request by stianjensen**
This removes EOL python and django versions from testing, and adds
Django 4.0 and Python 3.10, which are now available.

https://www.djangoproject.com/download/
https://endoflife.date/python

### CODE REVIEW

**Comment by madisona** [comment]
Thank you @stianjensen 

It looks like Django 4 is not compatible with Python 3.7.  Would you please adjust that piece?

image

**Comment by stianjensen** [comment]
Updated to only test Python 3.7 with Django 2.2 and Django 3.2

**Comment by madisona** [comment]
Thanks @stianjensen - The CI is still failing. It looks like maybe it needs to have quotes around `'3.10'`.  

The github actions fails because it is trying to pull python 3.1. (yaml parsing appears to truncate the zero because it thinks it is a number if not wrapped in quotes).  https://github.com/actions/setup-python/issues/160

**Comment by stianjensen** [comment]
Let's try this with everything in quotes, then :+1:

**Comment by madisona** [comment]
@stianjensen Looks like you accidentally did a 1 instead of '  so now it is coming as 13.10

**Comment by stianjensen** [comment]
Hah, sorry for all the back-and-forth! These things are always a bit tricky to test locally instead of on CI 😅

**Comment by madisona** [comment]
> Hah, sorry for all the back-and-forth! These things are always a bit tricky to test locally instead of on CI 😅

No worries - I appreciate your contribution!

**Pull request merged**
