### PR TITLE
Make compatible with Django 1.10

### PR DESCRIPTION
**Pull request by Duologic**
Warning: I am not a developer, I'm just hacking the code to work for me. Please be gentle on your comments.

For a personal project, I would like to use this library in a Django 1.10 project. I've removed a few deprecated things:

* django.db.models.field.subclassing.SubfieldBase is removed.
* [Field.get_prep_lookup() and Field.get_db_prep_lookup() methods are removed](https://docs.djangoproject.com/en/1.10/releases/1.10/#field-get-prep-lookup-and-field-get-db-prep-lookup-methods-are-removed)

~~I don't know how this would act towards older Django versions.~~ I've ran the tests which required me to put a workaround in several tests as Model.objects.create() didn't return the GeoPt() object. This has something to do with the data not being retrieved from the database with `from_db_value` and thus also not calling `to_python`. If someone can propose a better solution here, that'd be great. I've glanced at some solutions doing this with a `clean()` or `refresh_from_db()` on it, but didn't see an immediate solution.

I've also added support for testing against multiple Django versions and expanded the number of Python interpreters to reflect the Django support. See here:
* https://docs.djangoproject.com/en/1.7/faq/install/#what-python-version-can-i-use-with-django
* https://docs.djangoproject.com/en/1.10/faq/install/#what-python-version-can-i-use-with-django

This is also related to https://github.com/madisona/django-google-maps/issues/16

To keep maintenance possible for this project, I'd propose dropping support for Django 1.6 and 1.7.  But that decision is up to the maintainer.

### CODE REVIEW

**Comment by madisona** [comment]
@Duologic Thanks for your contribution! I'm good with dropping support for django <= 1.7. We'll just need to bump the major version to 0.6 and also update the readme to be clear which versions of django are supported.  I created another pull request #19 to bump the sample app to work with django 1.8+

Would you mind adjusting the pull request to only keep support for django 1.8+?

**Comment by Duologic** [comment]
Awesome, I'll check it out somewhere this week.

**Comment by Duologic** [comment]
I've updated my pull request to only support Django 1.8+ and Python versions 2.7, 3.4 and 3.5. I also ditched support for Python 3.3 as only Django 1.8 runs on it.

Also in this commit, ditched support for South as this has been replaced by Django's internal mechanism in Django 1.7.

Pull request https://github.com/madisona/django-google-maps/pull/19 from @madisona might also want to pull in these changes.

**Comment by jamiecounsell** [comment]
Hey guys, would love to see this finished. Let me know if there's anything I can do to help.

**Comment by Duologic** [comment]
As for the pull request, I think it is ready. Feel free to do some reviewing on it.

For merging and releasing, I'd suggest we be patient until the maintainer has some time. ;-)

**Comment by madisona** [comment]
Looks good to me. Thank you for your contribution!

**Pull request merged**
