### PR TITLE
Responsive map

### PR DESCRIPTION
**Pull request by tsredanovic**
References this issue: https://github.com/madisona/django-google-maps/issues/73

### CODE REVIEW

**Comment by madisona** [comment]
would you mind updating the pull request to add this to the css?  

```
@media (min-width: 825px) {
    .map_canvas_wrapper {margin-left: 170px;}
}
```

I believe that should make the address field responsive and still maintain structure and alignment on larger screens

**Comment by madisona** [comment]
thanks @tsredanovic! What version of Django are you using? It's possible the breakpoint may be different between the versions we're using. I've tested with `Django==2.2.6` and point where the field drops below the label is 824px.

**Comment by tsredanovic** [comment]
That's probably it. I'm using `Django==3.1.7` which has the admin nav sidebar that messes it all up. When the navbar is collapsed then that's the difference in pixels between yours 824px and mine 850px. I have also realized that my 850px (or any other constant value) is no good for `Django==3.1.7` since the admin nav sidebar can also be extended which distorts the map again.
OK with nav sidebar collapsed:
nav_sidebar_collaped
NOT OK with nav sidebar extended:
nav_sidebar_extended
I think we should look into making the `margin-left` relative some way which would always put it right under the address search box instead of having it as fixed `170px` value (I'm not really great with html, css though) or have the `margin-left` removed completely (simpler solution I guess).

**Comment by madisona** [comment]
@tsredanovic - I haven't used Django 3 much yet. Are there any classes or anything that could be used to indicate when the side menu is expanded, so we could change the behavior?

**Comment by madisona** [comment]
@tsredanovic - at least on django 3, does the following in google-maps-admin.css seem to be doing what you'd expect in all circumstances, whether the side bar is visible or not?

```
@media (min-width: 848px) {
    .map_canvas_wrapper {margin-left: 170px;}
    .main.shifted .map_canvas_wrapper {margin-left: 0;}
}
@media (min-width: 1118px) {
    .main.shifted .map_canvas_wrapper {margin-left: 170px;}
}

#id_address {width: 40em;}
.map_canvas_wrapper {width: 100%;}
#map_canvas {width: 100%; height: 40em;}
```

**Comment by tsredanovic** [comment]
@madisona Yeah, just tested it out and it works like a charm for each state of side bar. Also made a commit with it. Hope it works on Django 2 as well.

**Comment by madisona** [comment]
seeking feedback.  These adjustments look great with Django 3.  In Django 2 there would be ~24px where the map jumps to the left at 100% width, before the rest of the input field moves below the label.  My perspective is that it looks ok this way, but I want to be respectful of others. 
 Would there be any objection to this change?

image

**Pull request merged**
