### PR TITLE
Add support for Django REST framework

### PR DESCRIPTION
**Pull request by elcolie**
Hi
Since I don't know how tot make a package. 
Then I add some code here and hope you consider it for next release.

1. I provide the logic how to validate the `latitude, longitude`. Actually I want it to be a single field like `GeolocationField`
1. `REST` url for demo
1. `mystatic` directory for quickly demo the original example
1. Remove `readonly` from model admin. Since I feel convenient to see it quickly in  the first run

### CODE REVIEW

**Comment by madisona** [comment]
Hi @elcolie thanks for your contribution. Can you help me understand a little better what you are trying to solve or make more clear to users with the adjustments to the sample application?

**Comment by elcolie** [comment]
@madisona You response so fast. Things I want to solve are as follows
Sorry for poor explanation

1. **Boilerplate**: In `settings.py` I add `mystatic` Because first time I ran into the problem on this thing
1. **REST**: I provide API `/api/sample` in order to show my `validator`. And hopefully you can be able promote it to become `GeolocationField` not `CharField+Validator` like mine. I don't know how to make the `SerializerField`.
1. **Admin UX**. First time I used I felt so upset that I cannot save the instance. Almost switch out from your package. Therefore I want it to be able to do `save` from the `admin` page in the first contact. You can reuse my validator on this field. I had tried some invalid value and your form does validate the input then why not let it open to `save`?

**Comment by madisona** [comment]
Thanks, I think I see what you mean.  I'd suggest looking at the `CharField` object. I think what you're suggesting is to automatically add the validator to the `GeoLocationField` object (like the CharField does with `MaxLengthValidator`.  Go ahead implement it by adding the validator, but please make sure to add test coverage.

If you'd like to contribute the validator, please do it in a pull request where that is the only change. I don't think I'll add the other things (static files work just fine on a clean install of this repository, and the geolocation field in this sample is intended to be readonly as it is updated by a change in the address, not the other way around.

Thanks for helping make this project better! 

~ aaron

**Comment by elcolie** [comment]
Understood. Unfortunately in Thailand `address` field in the Google still need more improvement. Therefore I normally use manual pin point.

**Pull request closed without merging**
