### PR TITLE
fixed bug which didnt call try/except block correctly

### PR DESCRIPTION
**Pull request by dlenskyi**
If you will try to save a single number or word without comma, then it will cause 500 error (not enough values to unpack (expected 2, got 1)), same if there will be 3+ comma separated values. Thats why because you return exception to the place where you called this method (53 line in fields.py) and, therefore, try/except block didn't work correctly

### CODE REVIEW

**Comment by dlenskyi** [comment]
@madisona Do you have a tox.ini file somewhere or should I write it by my own and then run tests?

**Comment by dlenskyi** [comment]
@madisona tests added :)

**Comment by madisona** [comment]
thank you @dlenskyi

**Comment by dlenskyi** [comment]
@madisona thank you for this cool library :)

**Pull request merged**
